name: R5A06_DevAvancee_TP3

services:
  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: orders-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - service-network

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - service-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      - users-service
      - orders-service
    ports:
      - "3000:3000"
    networks:
      - service-network

networks:
  service-network:
    driver: bridge